mainsys/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from mainsys.settings import APP_ROOT, APP_MODELS, APP_VIEWS, APPS_CANNOT_INTSALL

urlpatterns = [
    path('muadmin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

# 根据wlapps里的目录进行动态添加url
for ap in os.listdir(APP_ROOT):
    if ap not in APPS_CANNOT_INTSALL and os.path.isdir(os.path.join(APP_ROOT, ap)) and \
            os.path.exists(os.path.join(os.path.join(APP_ROOT, ap), "__init__.py")) and \
            os.path.exists(os.path.join(os.path.join(APP_ROOT, ap), "urls.py")):
        urlpatterns.append(path("", include(ap + ".urls")))

# 根据wlapps里的目录进行动态添加url
for ap in os.listdir(APP_MODELS):
    if ap not in APPS_CANNOT_INTSALL and os.path.isdir(os.path.join(APP_MODELS, ap)) and \
            os.path.exists(os.path.join(os.path.join(APP_MODELS, ap), "__init__.py")) and \
            os.path.exists(os.path.join(os.path.join(APP_MODELS, ap), "urls.py")):
        urlpatterns.append(path("", include(ap + ".urls")))

# 根据wlviews里的目录进行动态添加url
if os.path.exists(APP_VIEWS):
    for ap in os.listdir(APP_VIEWS):
        if ap not in APPS_CANNOT_INTSALL and os.path.isdir(os.path.join(APP_VIEWS, ap)) and \
                os.path.exists(os.path.join(os.path.join(APP_VIEWS, ap), "__init__.py")) and \
                os.path.exists(os.path.join(os.path.join(APP_VIEWS, ap), "urls.py")):
            urlpatterns.append(path("", include(ap + ".urls")))

xyapps/accounts/forms.py
import logging

from django import forms
from django.contrib.auth import authenticate
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.forms.fields import CharField, MultiValueField
from xyapps.utils.common_c import isTelephoneFormat

User = get_user_model()
add_log = logging.getLogger('error')


# 登录的表单
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名")
    password = forms.CharField(label="密码", widget=forms.PasswordInput(render_value=False))

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        self._user = authenticate(username=username, password=password)
        if self._user is None:
            raise forms.ValidationError("无效的用户名和密码")
        elif not self._user.is_active:
            raise forms.ValidationError("您的账户未激活")
        return self.cleaned_data

    def save(self):
        return getattr(self, "_user", None)


# 随机码验证的表单
class RandomCodeVerifyForm(forms.Form):
    from xyapps.captcha.fields import CaptchaField
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super(RandomCodeVerifyForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        super(RandomCodeVerifyForm, self).save(*args, **kwargs)


# 注册表单
class SignupForm(forms.ModelForm):
    phone = forms.CharField(label=_("电话号码"), )
    code = forms.CharField(label=_("验证码"), )
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput(render_value=False))
    password2 = forms.CharField(label=_("Password (again)"), widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = User
        fields = ("phone", "code", "username", "password1", "password2",)

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        user_fields = [i.attname for i in User._meta.get_fields() if hasattr(i, "attname")]
        for field in self.fields:
            if field in user_fields:
                self.fields[field].required = True
                if field.startswith("password"):
                    self.fields[field].widget.attrs["autocomplete"] = "off"
                    self.fields[field].widget.attrs.pop("required", "")

    def clean_username(self):
        username = self.cleaned_data.get("username")
        # 判断用户名是否输入非法字符
        if username.lower() != slugify(username).lower():
            raise forms.ValidationError(ugettext("用户名无效，请使用字符以及数字组合"))
        # 对username进行查询，是否进行过注册
        lookup = {"username__iexact": username}
        try:
            User.objects.exclude(id=self.instance.id).get(**lookup)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(ugettext("该用户已经注册，请直接登录"))

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        # 匹配电话号码
        self.phone = isTelephoneFormat(phone)
        if self.phone is None:
            raise forms.ValidationError(ugettext("输入的邮箱或者电话号码无效"))
        else:
            return self.phone

    def clean_code(self):
        """
        To verify the input code equal to SMS code
        """
        code = self.cleaned_data.get("code")
        phone = self.cleaned_data.get("phone")
        from django.core.cache import cache

        if cache.get("random_code" + phone) is None:
            raise forms.ValidationError("短信验证码已失效")
        elif code != cache.get("random_code" + phone):
            raise forms.ValidationError("请确认短信中的验证码")
        else:
            return code

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1:
            if password1 != password2:
                raise forms.ValidationError(ugettext("两次输入的密码不同"))
            if len(password1) < 6:
                raise forms.ValidationError(ugettext("密码至少6位"))
        return password2

    def save(self, *args, **kwargs):
        kwargs["commit"] = False
        super(SignupForm, self).save(*args, **kwargs)
        password = self.cleaned_data.get("password1")
        username = self.cleaned_data.get("username")
        user = User.objects.create_user(username=username, password=password)
        # 开发平台创建用户时创建api用户
        return user

templates/xysite/base.html
<!DOCTYPE html>
{% load static %}

<html class="no-js" lang="zh-CN">
{% block html_head %}
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="format-detection" content="telephone=no">
        <meta name="renderer" content="webkit|ie-stand|ie-comp">
        <meta http-equiv="Cache-Control" content="no-siteapp"/>
        <meta http-equiv="x-dns-prefetch-control" content="on"/>
        <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
        <meta name="description"
              content="{% block meta_description %}{% endblock %}">
        <title>
            {% block meta_title %}首页{% endblock %}
            {% block main_title %} | {% endblock %}
        </title>
        <link rel="shortcut icon" href="{% static "xysite/img/favicon.png" %}">

        <link type="text/plain" href="/humans.txt" rel="author">
        {% block main_css %}
            <link rel="stylesheet" href="https://oss.elements.org.cn/opensource/amazeui-2.7.2/css/amazeui.min.css">
        {% endblock %}
        {% block extra_css %}
            <link rel="stylesheet" href="{% static 'xysite/css/saas.css' %}">
        {% endblock %}
        {% block unique_css %}{% endblock %}

        {% block main_js %}
                <script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
                <script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
            <script src="https://oss.elements.org.cn/opensource/jquery-2.2.4.min.js"></script>
            <script src="https://oss.elements.org.cn/opensource/amazeui-2.7.2/js/amazeui.min.js"></script>
        {% endblock %}
        {% block extra_js %}{% endblock %}
        {% block extra_head %}{% endblock %}
    </head>
{% endblock %}

<body>
{% block wlmain %}
{% endblock %}
{% block footer_js %}
    <script src="{% static "xysite/js/ajaxCookieSet.js" %}"></script>
    <script src="{% static "xysite/js/saas.js" %}"></script>
{% endblock %}
</body>
</html>

templates/xysite/login.html
{% extends "xysite/base.html" %}
{% load static %}
{% block header %}{% endblock %}
{% block footer %}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "xysite/css/login.css" %}">
{% endblock %}

{% block wlmain %}
    <div class="bm-wrap-bg">
        <div class="login-box">
            <h2>登陆系统</h2>
            <div class="clear"></div>

            <form id="login" method="post"
                  {% if form.is_multipart %}enctype="multipart/form-data" {% endif %}>
                <fieldset>
                    <div class="login-form">
                        <div class="user-name">
                            <label for="username"><i class="am-icon-user"></i></label>
                            <input type="text" name="username" class="am-form-field js-pattern-username" id="user"
                                   placeholder="请输入用户名" required minlength="2" maxlength="20">
                        </div>
                        <div class="user-pass">
                            <label for="password"><i class="am-icon-lock"></i></label>
                            <input type="password" name="password" id="password" class="am-form-field"
                                   placeholder="请输入密码" required minlength="6" maxlength="30">
                        </div>
                    </div>

                    <div class="login-links">
                        <a href="/accounts/signup/" class="am-fr">注册账号</a>
                        <br/>
                    </div>

                    <div class="am-cf bm-submit-login-wrap">
                        <input type="submit" id="submit" value="登 录" class="am-btn am-btn-primary am-btn-sm">
                    </div>

                    <div class="login_errors">
                        {% if form.non_field_errors %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}

{% block footer_js %}
    <script src="{% static 'xysite/js/ajaxCookieSet.js' %}"></script>
    <script src="https://oss.elements.org.cn/opensource/others/particles2.js"></script>
    <script src="{% static  'xysite/js/login.js' %}"></script>
    <script>
        if (window != top) top.location.href = location.href;
    </script>
{% endblock %}

templates/xysite/signup.html
{% extends "xysite/base.html" %}
{#{% load static %}#}

{% block header %}{% endblock %}
{% block footer %}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{%  static "xysite/css/login.css" %}">
{% endblock %}

{% block wlmain %}
    <div class="bm-wrap-bg">
        <div class="login-box signup-box">
            <h2>注册系统</h2>
            <div class="clear"></div>

            <form id="signup" method="post" class="am-form"
                  {% if form.is_multipart %}enctype="multipart/form-data" {% endif %}>
                <fieldset>
                    <div class="login-form signup-form">
                        <div class="am-form-group user-phone">
                            <label for="phone"><i class="am-icon-phone"></i></label>
                            <input type="text" class="am-form-field js-pattern-phone" name="phone" id="id_phone"
                                   placeholder="请输入手机号" required data-validation-message="请输入正确的手机号">
                        </div>

                        <div class="am-form-group verification">
                            <label for="code"><i class="am-icon-code"></i></label>
                            <input type="text" class="am-form-field" name="code" id="id_code"
                                   placeholder="手机验证码" minlength="3" maxlength="6"
                                   data-validation-message="请确认短信中的验证码">
                            <span class="btn" id="sendMobileCode">获 取</span>
                        </div>

                        <div class="am-form-group user-username">
                            <label for="username"><i class="am-icon-user"></i></label>
                            <input type="text" class="am-form-field js-pattern-username" name="username"
                                   id="id_username" placeholder="用户名/昵称" required
                                   data-validation-message="中文、字母、数字、@_-，2-16位">
                        </div>

                        <div class="am-form-group user-pass user-pass1">
                            <label for="password1"><i class="am-icon-lock"></i></label>
                            <input type="password" class="am-form-field js-pattern-password" name="password1"
                                   id="password1" placeholder="设置密码" required
                                   data-validation-message="请输入6-16位非空字符密码">
                        </div>

                        <div class="am-form-group user-pass user-pass2">
                            <label for="passwordRepeat"><i class="am-icon-lock"></i></label>
                            <input type="password" class="am-form-field" name="password2" id="passwordRepeat"
                                   placeholder="确认密码" data-equal-to="#password1" required
                                   data-validation-message="密码不一致，请确认">
                        </div>

                        <div class="am-cf">
                            <input type="submit" id="submit" value="注 册"
                                   class="am-btn am-btn-secondary am-btn-sm am-fl">
                        </div>
                    </div>
                </fieldset>
            </form>

            <form method="post" class="am-form am-form-horizontal" id="random_code_form">
                {% csrf_token %}
                <div class="am-form-group random_code_verification">
                    <label for="captcha_1"><i class="am-icon-code-fork"></i></label>
                    <input type="text" name="captcha_1" id="id_captcha_1"
                           class="am-form-field id_captcha_1" placeholder="图片验证码" maxlength="4" required="true"
                           style="width: 61%;border: 1px solid #eee;"/>

                    <div id='captcha'>{{ random_code.captcha }}</div>
                </div>
                <div style="display:none;">
                    <input id="random_code_verify_btn" type="submit" value="进行验证"/>
                </div>
            </form>
        </div>
    </div>

    <div class="am-modal am-modal-alert" tabindex="-1" id="signup_sucess">
        <div class="am-modal-dialog">
            <div class="am-modal-bd" style="padding: 40px 0">
                恭喜您注册成功，跳转登录页面中...
            </div>
            <div class="am-modal-footer">
                <span class="am-modal-btn" data-am-modal-confirm>确定</span>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_js %}
    <script src="{% static "xysite/js/ajaxCookieSet.js" %}"></script>
    <script src="https://oss.elements.org.cn/opensource/others/particles2.js"></script>
    <script src="{% static "xysite/js/login.js" %}"></script>
    <script src="{% static "xysite/js/signup.js" %}"></script>
{% endblock %}